apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  containers:
    - name: demo-app
      image: geku/go-app:0.1
      env:
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      ports:
        - name: http
          containerPort: 5000
          hostPort: 5000
