apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: crash-demo
  labels:
    app: crash-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-app
  template:
    metadata:
      labels:
        app: crash-app
    spec:
      containers:
      - name: crash-demo
        image: geku/workshob-crash
        env:
        - name: PASSWORD
          value: abc
        ports:
        - containerPort: 3000
