apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  volumes:
  - name: k8s
    hostPath:
      path: "/etc/kubernetes"
  containers:
  - name: kube-controller-manager
    image: gcr.io/google_containers/kube-controller-manager-amd64:v1.7.8
    command:
    - kube-controller-manager
    - "--address=127.0.0.1"
    - "--master=http://127.0.0.1:8080"
    volumeMounts:
    - name: k8s
      readOnly: true
      mountPath: "/etc/kubernetes/"
