apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: etcd
      image: quay.io/coreos/etcd:v3.1.5
      args:
        - "/usr/local/bin/etcd"
        - "--name=etcd1"
        - "--advertise-client-urls=http://127.0.0.1:2379"
        - "--listen-client-urls=http://0.0.0.0:2379"
        - "--listen-peer-urls=http://0.0.0.0:2380"
        - "--data-dir=/var/lib/etcd/data"
        - "--wal-dir=/var/lib/etcd/wal"
        - "--initial-advertise-peer-urls=http://127.0.0.1:2380"
        - "--initial-cluster=etcd1=http://127.0.0.1:2380"
        - "--initial-cluster-state=new"
        - "--initial-cluster-token=demo-cluster"
      ports:
        - name: client
          containerPort: 2379
          protocol: "TCP"
        - name: peer
          containerPort: 2380
          protocol: "TCP"
      volumeMounts:
        - name: etcd
          mountPath: /var/lib/etcd
  volumes:
    - name: etcd
      hostPath:
        path: /var/lib/etcd
