apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/kube-proxy-amd64:v1.7.8
    command:
    - kube-proxy
    - --proxy-mode=iptables
    - --master=http://127.0.0.1:8080
    - --cluster-cidr=172.17.0.0/16
    - --v=2
    securityContext:
      privileged: true
    volumeMounts:
    - name: dbus
      mountPath: /var/run/dbus
  volumes:
  - name: dbus
    hostPath:
      path: /var/run/dbus
